POST http://localhost:4000/api/auth/signup
Content-Type: application/json

{
    "email": "mail@mail.mail",
    "password": "best passwor in the world lol lol lol 1234"
}

###

POST http://localhost:4000/api/auth/login 
Content-Type: application/json

{
    "email": "mail@mail.mail",
    "password": "best passwor in the world lol lol lol 1234"
}

# type here:
###